cookie:
  expiry_days: 30
  key: super_secret_key
  name: tech_talent_v2
credentials:
  usernames:
    admin:
      email: admin@techtalent.com
      name: Admin
      password: $2b$12$Ivtkxk4DQkzlZ7.KRH/gIeAdp8Pm9r3VBtnaGEcPDmwzoQeq6vNSu
